# This file is automatically generated, and should not be changed. There is
# probably little reason to edit this file anyway, since it should already
# contain all information for the EFM32GG11 family of CPUs.

# Series - Architecture - Flash base - Flash size - SRAM base - SRAM size - Crypto? - TRNG? - Radio?
EFM32_INFO_efm32gg11b820f2048gl192  = 0 cortex-m4f 0x00000000 0x00200000 0x20000000 0x00080000 0 0 0
